"""Init migration 2

Revision ID: 00002
Revises: 00001
Create Date: 2025-10-17 19:56:33.913237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00002'
down_revision: str | None = '00001'
branch_labels: Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_column('missions', 'name')
    # ### end Alembic commands ###
