"""Init migration

Revision ID: 00001
Revises: 
Create Date: 2025-10-17 18:59:58.670092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00001'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spy_cats',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spy_cats_breed'), 'spy_cats', ['breed'], unique=False)
    op.create_index(op.f('ix_spy_cats_created_at'), 'spy_cats', ['created_at'], unique=False)
    op.create_index(op.f('ix_spy_cats_id'), 'spy_cats', ['id'], unique=False)
    op.create_index(op.f('ix_spy_cats_name'), 'spy_cats', ['name'], unique=False)
    op.create_index(op.f('ix_spy_cats_years_of_experience'), 'spy_cats', ['years_of_experience'], unique=False)
    op.create_table('missions',
    sa.Column('cat_id', sa.UUID(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['spy_cats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_cat_id'), 'missions', ['cat_id'], unique=False)
    op.create_index(op.f('ix_missions_complete'), 'missions', ['complete'], unique=False)
    op.create_index(op.f('ix_missions_created_at'), 'missions', ['created_at'], unique=False)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_table('targets',
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_complete'), 'targets', ['complete'], unique=False)
    op.create_index(op.f('ix_targets_country'), 'targets', ['country'], unique=False)
    op.create_index(op.f('ix_targets_created_at'), 'targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_mission_id'), 'targets', ['mission_id'], unique=False)
    op.create_index(op.f('ix_targets_name'), 'targets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_name'), table_name='targets')
    op.drop_index(op.f('ix_targets_mission_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_created_at'), table_name='targets')
    op.drop_index(op.f('ix_targets_country'), table_name='targets')
    op.drop_index(op.f('ix_targets_complete'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_created_at'), table_name='missions')
    op.drop_index(op.f('ix_missions_complete'), table_name='missions')
    op.drop_index(op.f('ix_missions_cat_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_spy_cats_years_of_experience'), table_name='spy_cats')
    op.drop_index(op.f('ix_spy_cats_name'), table_name='spy_cats')
    op.drop_index(op.f('ix_spy_cats_id'), table_name='spy_cats')
    op.drop_index(op.f('ix_spy_cats_created_at'), table_name='spy_cats')
    op.drop_index(op.f('ix_spy_cats_breed'), table_name='spy_cats')
    op.drop_table('spy_cats')
    # ### end Alembic commands ###
